title: Lucas Garay
#logo: "pic.jpg"
#round-logo: true
description: Welcome to my homepage, you can contact me by email if you have any questions :D

social-network-links:
  email: "lucasgaray095@gmail.com"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: pic.jpg

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: pic.jpg

theme: minimal-mistakes-jekyll #jekyll-theme-minimal
