title: Lucas Garay
avatar: "pic.jpg"
round-avatar: true
description: Welcome to my homepage, you can contact me by email if you have any questions :D
theme: jekyll-theme-minimal
email: "lucasgaray095@gmail.com"
