title: Lucas Garay
logo: "/assets/img/pic.jpg"
description: Welcome to my homepage, you can contact me by email if you have any questions :D
theme: jekyll-theme-minimal
show_downloads: false
author:
  name: GitHub User
  email: your-email@domain.com
